feat: add match transaction support to proto3
naomijub/gXTDB pull request #21
Opened 2023-05-31 03:10 UTC by jerielverissimo

2023-06-01 19:05 UTC, naomijub requested changes
Overall looks good, I would just change the proto to use option datetime

2023-06-01 19:05 UTC, naomijub commented on resources/transactions.proto
> +  string valid_time = 4;
We added the OptionString type for this cases. It is important because of the usage in Rust that Converts it to Option<String>. I would strongly suggest creating an `OptionDatetime` for this, so in the client side we can convert `Option<Datetime> to `OptionDatetime`

2023-06-01 19:06 UTC, naomijub commented on resources/transactions.proto
> +  string valid_time = 4;
This would create the foundation for this task https://github.com/naomijub/gXTDB/issues/5

2023-06-02 05:18 UTC, naomijub commented on resources/transactions.proto
> +message Empty {}
This is not part of transactions only, as it is used for `status`, maybe we can create a helper.proto that contains Empty, OptionString and OptionDatetime, but I would just leave them in service.proto for now

2023-06-03 14:01 UTC, jerielverissimo commented on resources/transactions.proto
> +message Empty {}
Yep, I had to move to the transaction because I faced a cyclic importing from service and transactions.

2023-06-03 16:23 UTC, naomijub approved these changes

2023-06-03 16:23 UTC, merged

2023-06-03 19:53 UTC, pfeodrippe commented on src/gxtdb/adapters/tx_log.clj
> +    [::xt/match (into {:xt/id (utils/->id id-type id)} (json/value-record->edn {:kind {:struct-value document}}))]))
Just trying to understand the project, so some questions.

1. Should we also handle `:valid-time` here from the transaction or is it handled somewhere else?
1. Should it match the `[::xt/match entity-id expected-doc valid-time]` form? 
    1. It seems we are only handling expected-doc

2023-06-03 20:38 UTC, naomijub commented on src/gxtdb/adapters/tx_log.clj
> +    [::xt/match (into {:xt/id (utils/->id id-type id)} (json/value-record->edn {:kind {:struct-value document}}))]))
There is another issue for time values, as they were optional fields, I left it for later